services:
  spark-streaming:
    build: .
    container_name: spark-streaming
    hostname: spark-streaming
    volumes:
      - ./:/opt/app
      - checkpoints:/opt/checkpoints
    env_file:
      - .env
    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[2]
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.2,org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.9.2,org.apache.iceberg:iceberg-aws-bundle:1.9.2,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.102.5
      - /opt/app/consumer.py
    networks:
      - spotify-analytics

volumes:
  checkpoints:

networks:
  spotify-analytics:
    external: true
    name: spotify-analytics
